use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde::Deserialize;

#[derive(Deserialize)]
struct Config {
    #[serde(default)]
    font: Vec<FontEntry>,
    #[serde(default)]
    icon: Vec<IconEntry>,
}

#[derive(Deserialize)]
struct FontEntry {
    name: String,
    path: String,
    sizes: Vec<u32>,
}

#[derive(Deserialize)]
struct IconEntry {
    name: String,
    path: String,
    size: u32,
}

const ATLAS_NAME: &str = "keyboard";

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=config.toml");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR not set"));
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));

    let config_path = manifest_dir.join("config.toml");
    let config_src = std::fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", config_path.display()));
    let config: Config = toml::from_str(&config_src)
        .unwrap_or_else(|e| panic!("parsing {}: {e}", config_path.display()));

    let atlas_toml_path = out_dir.join("atlas.toml");
    std::fs::write(
        &atlas_toml_path,
        generate_atlas_toml(&config, &manifest_dir),
    )
    .expect("writing generated atlas.toml");

    if let Err(e) = assets::builder::pack_atlas(&atlas_toml_path, &out_dir) {
        println!("cargo:warning=atlas packing failed: {e:?}");
    }

    std::fs::write(out_dir.join("icons_gen.rs"), generate_icons_rs(&config))
        .expect("writing icons_gen.rs");
}

fn generate_atlas_toml(config: &Config, manifest_dir: &Path) -> String {
    let abs = |p: &str| manifest_dir.join(p).display().to_string();

    let mut s = String::from("# generated by build.rs from config.toml — do not edit\n");
    let _ = writeln!(s, "[[atlas]]\nname = \"{ATLAS_NAME}\"\n");

    for font in &config.font {
        let sizes = font
            .sizes
            .iter()
            .map(|n| n.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(
            s,
            "[[atlas.font]]\nname = \"{}\"\npath = \"{}\"\nsizes = [{}]\n",
            font.name,
            abs(&font.path),
            sizes,
        );
    }

    for icon in &config.icon {
        let _ = writeln!(
            s,
            "[[atlas.sprite]]\nname = \"{}\"\npath = \"{}\"\nwidth = {}\nheight = {}\n",
            icon.name,
            abs(&icon.path),
            icon.size,
            icon.size,
        );
    }

    s
}

fn generate_icons_rs(config: &Config) -> String {
    let atlas_upper = to_const_name(ATLAS_NAME);
    let mut s = String::from("// generated by build.rs from config.toml — do not edit\n");
    s.push_str(
        "/// Resolve a symbolic icon name to its baked atlas sprite region.\n\
         pub fn icon_region(name: &str) -> Option<::assets::SpriteRegion> {\n    \
         match name {\n",
    );
    for icon in &config.icon {
        let _ = writeln!(
            s,
            "        {:?} => Some(crate::atlas::{}_{}),",
            icon.name,
            atlas_upper,
            to_const_name(&icon.name),
        );
    }
    s.push_str("        _ => None,\n    }\n}\n");
    s
}

fn to_const_name(s: &str) -> String {
    s.to_uppercase().replace('-', "_").replace(' ', "_")
}
